version: "3.7"

services:
  secondary:
    image: atsigncompany/secondary:dess
    command: "-a ${ATSIGN} -p ${PORT} -s ${SECRET}"
    ports:
      - target: $PORT
        published: $PORT
    volumes:
      - ~/atsign/etc/live/${DOMAIN}:/atsign/certs
      - ~/atsign/etc/archive/${DOMAIN}:/archive/${DOMAIN}
      - ~/atsign/${ATSIGN}:/atsign/storage
    networks:
      second: {}

networks:
  second:
    external: true
    name: secondaries
