version: "3"

services:
  shepherd:
    image: mazzolino/shepherd:latest
    environment:
      TZ: 'US/PST'
      SLEEP_TIME: '30m'
      VERBOSE: 'true'
      FILTER_SERVICES: 'label=com.docker.stack.image=cconstab/secondary'
      IMAGE_AUTOCLEAN_LIMIT: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager